### ISSUE TITLE
Incompatible with current version of minitest

### ISSUE THREAD

**Issue by gma** [itstommymorgan/nutrasuite#5]
In seattlerb/minitest@d43e87b19 support for the `@setup_hooks` instance variable and the `add_setup_hook` method was removed.

This prevents nutrasuite from working with current versions of minitest. Do you have any thoughts on whether or not it's worth fixing? I've no idea how many people are using nutrasuite + Tconsole these days (though I doubt it's just me…).

**Comment by itstommymorgan** [comment]
Hey Graham;

We haven't been using nutrasuite (or tconsole for that matter) for a
little over a year now at Treehouse as we've switched away from
minitest.

It looks like it might not be a difficult fix - it looks like they added
a new "LifecyleHooks" module to cover similar functionality:

http://yard.ruby-doc.org/stdlib-2.1.0/MiniTest/Unit/LifecycleHooks.html

But I'm honestly not sure that I'd be able to get to this in the near
future. Is this something you'd want to take a crack at?

On 04/10, Graham Ashton wrote:

> In seattlerb/minitest@d43e87b19 support for the `@setup_hooks` instance variable and the `add_setup_hook` method was removed.
> 
> This prevents nutrasuite from working with current versions of minitest. Do you have any thoughts on whether or not it's worth fixing? I've no idea how many people are using nutrasuite + Tconsole these days (though I doubt it's just me…).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wellbredgrapefruit/nutrasuite/issues/5

## 

Tommy Morgan
http://www.wellbredgrapefruit.com

**Comment by gma** [comment]
I'll be sticking with test-unit style assertions for the foreseeable future, so I think I'll take a look at how easy it would be to support minitest/spec describe blocks these days (maybe they've changed?), and if that's too hard I'll need to patch nutrasuite.

How do people cope without tconsole?! ;-)

**Comment by itstommymorgan** [comment]
I know that was rhetorical, but. :)

The team as a whole decided to switch to rspec, which has built-in some
of the functionality that tconsole provided for us with minispec.
Combine with that the fact that there was some difficulty (as I recall)
getting tconsole to work with rspec and the introduction of preloaders
like spring, the need kind of fell off for us.

On 04/14, Graham Ashton wrote:

> I'll be sticking with test-unit style assertions for the foreseeable future, so I think I'll take a look at how easy it would be to support minitest/spec describe blocks these days (maybe they've changed?), and if that's too hard I'll need to patch nutrasuite.
> 
> How do people cope without tconsole?! ;-)
> 
> Tommy Morgan notifications@github.com wrote:
> 
> > Hey Graham;
> > 
> > We haven't been using nutrasuite (or tconsole for that matter) for a
> > little over a year now at Treehouse as we've switched away from
> > minitest.
> > 
> > It looks like it might not be a difficult fix - it looks like they added
> > a new "LifecyleHooks" module to cover similar functionality:
> > 
> > http://yard.ruby-doc.org/stdlib-2.1.0/MiniTest/Unit/LifecycleHooks.html
> > 
> > But I'm honestly not sure that I'd be able to get to this in the near
> > future. Is this something you'd want to take a crack at?
> > 
> > On 04/10, Graham Ashton wrote:
> > 
> > > In seattlerb/minitest@d43e87b19 support for the `@setup_hooks` instance variable and the `add_setup_hook` method was removed.
> > > 
> > > This prevents nutrasuite from working with current versions of minitest. Do you have any thoughts on whether or not it's worth fixing? I've no idea how many people are using nutrasuite + Tconsole these days (though I doubt it's just me…).
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/wellbredgrapefruit/nutrasuite/issues/5
> > 
> > ## 
> > 
> > Tommy Morgan
> > http://www.wellbredgrapefruit.com 
> > 
> > —
> > Reply to this email directly or view it on GitHub.￼
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wellbredgrapefruit/nutrasuite/issues/5#issuecomment-40447666

## 

Tommy Morgan
http://www.wellbredgrapefruit.com
